# Generated by Django 2.2.16 on 2022-11-27 16:16

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221126_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[
                reviews.validators.validate_year], verbose_name='Год выпуска '
                                                           'произведения'),
        ),
    ]
